### ISSUE TITLE
Utility of `funnel` unclear

### ISSUE THREAD

**Issue by TartanLlama** [joboccara/pipes#10]
I don't see any documentation about `funnel`. It like the library should be implementable without it and that it adds unnecessary syntactic overhead.

**Comment by joboccara** [comment]
You're right. I was about to write how I couldn't make the library work without `funnel`, and the fact that you suggested that it seemed possible made give it another try.
And with this [fix](https://github.com/joboccara/pipes/commit/0a4f447758bb1c05318dd56b566a758183ffc2ec) funnel is now gone! The fix is that operator>>= now uses the detection idiom to guess if the left operand looks like a range.
Thanks a bunch! :)

**Comment by TartanLlama** [comment]
I haven't tested the fix, but it looks like it wouldn't work with types which have `begin` and `end` found through ADL.

**Comment by marzojr** [comment]
TartanLlama is correct, it will not work with ADL bagin and end. You need to do something like this:

```c++
namespace detail
{
namespace adl
{
using std:: begin;
using std::end;
template<typename T>
using begin_expression = decltype(begin(std::declval<T>()));
template<typename T>
using end_expression = decltype(end(std::declval<T>()));
}
using begin_expression = adl::begin_expression;
using end_expression = adl::end_expression;
template<typename Range>
constexpr bool range_expression_detected = detail::is_detected<begin_expression, Range> && detail::is_detected<end_expression, Range>;
```

**Comment by TartanLlama** [comment]
I think it'd need to be `std::declval<T&>`, but otherwise looks legit.

**Comment by joboccara** [comment]
Indeed, thanks. Fix submitted with [this commit](https://github.com/joboccara/pipes/commit/9fc76c0ff9670e31ff8b14afe3ebd0fc917a328b).

**Comment by TartanLlama** [comment]
Looks good, should be `std::declval<T&>` though
